### ISSUE TITLE
Error when serving app with Sass Loader (options has an unknown property 'includePaths')

### ISSUE THREAD

**Issue by JohanHeyvaert** [nrwl/nx-examples#100]
Hi,

I just cloned this repo. After running "npm install" and "ng serve cart" the below error is thrown.
I've searched where these options are set but unfortunately I cannot find it.
Any idea how to fix this?

Thanks & best regards,
Johan

ERROR in C:/Dev/nx-examples/libs/shared/header/index.scss 
(C:/Dev/nx-examples/node_modules/@nrwl/web/src/utils/third-party/cli-files/plugins/raw-css-loader.js!C:/Dev/nx-examples/node_modules/postcss-loader/src??embeddees/postcss-loader/src??embedded!C:/Dev/nx-examples/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-3!C:/Dev/nx-examples/libs/shared/header/index.scss)
**Module build failed** (from C:/Dev/nx-examples/node_modules/sass-loader/dist/cjs.js):
ValidationError: **Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'.** These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (C:\Dev\nx-examples\node_modules\schema-utils\dist\validate.js:85:11)
    at Object.loader (C:\Dev\nx-examples\node_modules\sass-loader\dist\index.js:36:28)

**Comment by JohanHeyvaert** [comment]
The products app is working though. Weird!

**Comment by meeroslav** [comment]
This solution uses `yarn` lock, so most likely running `npm install` caused some mismatched npm configuration.

Running `yarn` and then `nx serve cart` should produce no errors.
