### ISSUE TITLE
Why does the readme use "ng" command. What is ng?

### ISSUE THREAD

**Issue by gaggle** [nrwl/nx-examples#134]
Hi, maybe I'm overlooking something silly but I don't understand the readme when it says:
> Below are some plugins which you can add to your workspace:
> * Angular
>   * `ng add @nrwl/angular`
> * React
>   * `ng add @nrwl/react`

What is `ng`? Is it supposed to say `nx`? 🤔

**Comment by Steven-Harris** [comment]
Maybe I can help clear things up for you @gaggle , 

>Nx is a set of Angular CLI power-ups for modern development.

Nx was built off of @angular/cli and the README assumes @angular/cli has already been installed. 

More info about the `ng` command can be found [here](https://cli.angular.io/).

**Comment by DaSchTour** [comment]
It's confusing, especial with the add command. I'm getting either `The add command requires to be run in an Angular project, but a project definition could not be found.` (when using ng) or `Could not find project` (when using nx)

**Comment by meeroslav** [comment]
@DaSchTour, you are right. This readme is 2 years old and outdated. We will update it.

`ng add` is a feature of the angular CLI that installs the package and runs any necessary schematics. 
As NX workspace is not an angular solution, the given commands will no longer work.

You should use:
- `npm install --save-dev @nrwl/react` (or shorter `npm i -D @nrwl/react`)
- `yarn add --dev @nrwl/react`

This command adds the ability to your NX workspace to understand `react` projects. The same goes for `angular`, `nest`, `express` etc.
