### ISSUE TITLE
Why should we use ng g @nrwl/angular:app?

### ISSUE THREAD

**Issue by webmandman** [nrwl/nx-examples#142]
Normally, we'd use "ng g application myapp". The Nx Example readme shows "ng g @nrwl/angular:app myapp" to create an application. 

I have tried both ways within an Nx workspace and I didn't find any difference. 

Is there a difference?

**Comment by webmandman** [comment]
Well I found no difference. I compared files, and its all the same setup and generated code. 

As far as I can tell these are the same:
ng g application myapp <--> ng g @nrwl/angular:app myapp <--> nx g application myapp
ng g library mylib           <--> ng g @nrwl/angular:lib mylib <--> nx g library mylib

**Comment by meeroslav** [comment]
Hi @webmandman, if you are using just a basic generation by only providing a name, then there are no differences. However, `@nrwl/angular:app` provides some options which are `nx` specific and not supported by standard Angular CLI, such as `tags`, `backendProject`, etc. To get the full difference, run following in your terminal:
```bash
# standard ng schematics
ng g application --help

# nx schematics
nx g @nrwl/angular:app --help
```

**Comment by webmandman** [comment]
@meeroslav I ran those two commands, and they both produce the same help text. --tags and --backendProject are listed in the help text for both commands. 

Its been a little confusion for me. I wasn't sure for several weeks which was the  "correct" way to generate my code. I see  now its all the same, but now I know that maybe one day the generated code might change.

**Comment by AgentEnder** [comment]
Hey! Is your default schematics package listed as @nrwl/angular by any chance? Its possible you are calling the same schematic by mistake.

**Comment by webmandman** [comment]
Yes in my angular.json I have this:
```
  "cli": {
    "defaultCollection": "@nrwl/angular"
  },
```

**Comment by AgentEnder** [comment]
Here is the definition for @nrwl/angular:application. Note its alias "app". With a defaultCollection of @nrwl/angular, those two commands are executing the same schematic.

https://github.com/nrwl/nx/blob/master/packages/angular/collection.json#L14

**Comment by webmandman** [comment]
@AgentEnder  I wanted to know if I could continue with the angualr cli commands as I already know them, and I can. so that makes me feel comfortable for various reasons, specially when it comes to introducing it to teammates. I can also append the tag flag whenever I want and it works. I'll wait to see when nx complete changes the output and generated code or whatever else, but at the moment its the exactly the same.
