### ISSUE TITLE
[feature-request] - Do you have an ability to integrate NodeJS app within App/Lib?

### ISSUE THREAD

**Issue by HackPoint** [nrwl/nx-examples#17]
I would like to have the ability to use nodejs or any (server side) from workspace (app/lib) do you have that abilty integrated ? Or should I use only RESTful API?

**Comment by daniel-gwilt-software** [comment]
It would be really cool to have NRWL understand server apps as well.  Knowing if they're restful or GraphQL and providing linting and IDE hinting for the API in our Angular apps.  It would be nice if they had generators for typical typescript servers like Swagger and Appollo projects.  TypeORM and NestJS come to mind as well.

**Comment by Yonet** [comment]
@HackPoint we don't have the nodejs library ability but we are working on adding that feature.
@daniel-gwilt-software we might not add all that but we will add a schematics generator, so you can write your own extention easily.
