### ISSUE TITLE
Multiple applications on same port

### ISSUE THREAD

**Issue by StallionV** [nrwl/nx-examples#171]
Hello,

How can we run multiple applications on the same port just different base URL?
Assume we do not have access to backend since API calls are external

We are using next js  and adding basePath in next.config.js will render app on localhost/basepath but ports are still different
so instead of
app1 on localhost:4200
app2 on localhost:4300
We want
app1 on localhost:4200/app1
app2 on localhost:4200/app2 running in parallel.

**Comment by AnubhutiRoX** [comment]
I have same requirement.

**Comment by StalkAltan** [comment]
Hi @StallionV @AnubhutiRoX 

This isn't really an Nx issue. Your best bet for approaching this is to use something like Nginx to set up a reverse proxy.

Then the setup would be:

```
                            "/app1" redirects
nginx (or other software)          /=======>   app1 (running on some port not 4200)
                       ===========
          Port 4200                \========>  app2 (running on some port not 4200 or app1's port)
                             "/app2" redirects
```
