### ISSUE TITLE
Question - What branch contains all the working code?

### ISSUE THREAD

**Issue by netwobble** [nrwl/nx-examples#19]
Checking out each branch looks like the name corresponds with the readme file.  What branch contains the final working code?

Thanks
AJ

**Comment by seescode** [comment]
I just browsing this repo and came across your question.  It looks like master does contain the currently most up to date code.  If you look at the git branches you can see that master contains all the other code:

https://github.com/nrwl/nx-examples/network

**Comment by Yonet** [comment]
@netwobble as @seescode mentioned, all the branches are merged into master and updated with the latest version of nx. If you are looking for a version that works with a specific nx version, you can check out the commits. Thanks.
