### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SanderElias** [nrwl/nx-examples#21]
Where can I find the documentation where the use of create-nx-workspace (and it's options) is documented?

**Comment by klaascuvelier** [comment]
I found it in the course on [Enterprise Angular Playbook](angularplaybook): https://angularplaybook.com/courses/264974/lectures/4113736.

It's not really useable now as documentation, but might be used to generate it?

**Comment by Yonet** [comment]
Sorry for the late reply. 
@SanderElias @SanderElias you can find the updated documentation here: https://nrwl.io/nx.
