### ISSUE TITLE
Examples of how to use NX?

### ISSUE THREAD

**Issue by mcblum** [nrwl/nx-examples#22]
It's possible I've got something misconfigured but the folder structure I see when I use the generators doesn't match what's in the repo. For example when I generate a `lib` I see it created in `libs/{name}/apps/{appName}/src/lib.module.ts`.

We have a reasonably-sized app that I'm trying to keep control of but I'm a bit lost! Any help would be greatly appreciated.

**Comment by phl3x0r** [comment]
I have the same confusion going on..
Whenever I generate an app or a lib, a folder apps/appname is created.
"appname" seems to correspond with the apps[0] from .angular-cli.json
This seems like a bug to me, if not, please explain the intention of this.

**Comment by phl3x0r** [comment]
Also happens when generating services:
`$ ng generate service test-feature --app=zoo
  create apps/zoo/apps/defaultapp/src/app/test-feature.service.spec.ts (405 bytes)
  create apps/zoo/apps/defaultapp/src/app/test-feature.service.ts (117 bytes)`

**Comment by Springrbua** [comment]
I am facing the same problem and opened issue #250 for it, because I didn't find this one.  
This is a big Issue for me and I have to move all the generated files manually.

**Comment by Yonet** [comment]
@mcblum @phl3x0r, as @Springrbua pointed out, this looks like an issue closed now. If you are still having the issue, please file on nx repo. Nx-example repo is a good place to compare, or run locally to try to replicate an issue. Thank you for reporting. Closing this issue.

**Comment by mcblum** [comment]
Thanks @Yonet! I haven't seen the fix take place yet on our side but I'll make sure everything we have is up to date and try it again. Appreciate your hard work on Nx - it's really awesome.
