### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by voodoorider** [nrwl/nx-examples#23]
Due to assets (gif files) the repo is very big. Fresh check-out dir weighs ~725MB. Please compress the image files.

**Comment by Yonet** [comment]
@voodoorider thank you for reporting. I've deleted unused assets. If the size is still a concern, you can delete the school app and ar library. I will keep it there in case anyone is interested in the AR example. Demo app have an example now you can see here: https://nrwl.github.io/nx-examples/nx-examples/d3.
Closing.
