### ISSUE TITLE
Example Repo doesn't load

### ISSUE THREAD

**Issue by ndcunningham** [nrwl/nx-examples#27]
When i try to access the  example repo: https://nrwl.github.io/nx-examples/nx-examples I get a number of 404 errors. See Image

![image](https://user-images.githubusercontent.com/338948/37567497-4dcddf3e-2a9e-11e8-836e-c3c1209d359e.png)

**Comment by Yonet** [comment]
@ndcunningham thank you for reporting. Updated the build. Closing.
