### ISSUE TITLE
Workspace-specific schematics use case example

### ISSUE THREAD

**Issue by llioss** [nrwl/nx-examples#34]
Hi,
It would be very useful if you could add a workspace-specific schematics use case example in Readme.
Maybe we just have to follow the angular schematics docs ?

**Comment by Yonet** [comment]
@llioss nx is extending angular-cli. Workspace-specific schematics are still using `ng generate libs...` syntax. Only few doesn't exist on cli, like ngrx and affected. 

You can get a list of the nx specific commands by running:
```
npm run help
```

**Comment by llwt** [comment]
I'm in the same boat, looking at creating some space-specific schematics that extend the ones provided by Nx but finding it hard to get started with the minimal documentation available in the [docs](https://nrwl.io/nx/workspace-specific-schematics).

For example:

Once the schematic is generated, how do we register / call it, the screenshot in that doc doesn't show the executed command?

 
How would we extend the "lib" schematic to tweak a file that is generated, for example adding ci-specific config into the `karma.conf.js`?

**Comment by llioss** [comment]
As said @Yonet `npm run help` show : 
_**nx.js workspace-schematic <name>**  Runs a workspace schematic from the tools/schematics directory_

[AngularBlog schematics intro](https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2) show an example (_Collection_ section)
