### ISSUE TITLE
school-ui is not shared by other apps expect school, why put it in libs directory?

### ISSUE THREAD

**Issue by mingzhi5626** [nrwl/nx-examples#50]
this lib school-ui (https://github.com/nrwl/nx-examples/tree/master/libs/school-ui) which is not shared in other apps except school app (https://github.com/nrwl/nx-examples/tree/master/apps/school). Why do you put it in libs directory? This looks strange. My understanding is that all modules in libs are supposed to be shared across multiple apps, rather than used just in one dedicated app. I think this misleads novice to put app related modules/components in libs folder, not only shared modules/components. Thanks.

**Comment by Yonet** [comment]
> My understanding is that all modules in libs are supposed to be shared across multiple apps, rather than used just in one dedicated app.

@mingzhi5626 good assumption, but that is not what our intention. You can have common/shared in a library but also, you can have libraries for specific app use, or even specific feature. If you are working with a large team, this organization helps people to be able to work independently. Also, we can lazy load the modules in the feature/app specific libraries. Another advantage is affected:test and affected:build. If we have smaller libraries for each feature, we don't have to test or rebuild each time a change happens in one library. Hope I answered your question. 

I will add a FAQ section on the readme and add your question. We are working on a style-guide recommendation. Stay tuned for a blog post explaining how we organize our libraries. You are of course free to use it any way that works for you.
