### ISSUE TITLE
npm run affected:apps not working

### ISSUE THREAD

**Issue by dgroh** [nrwl/nx-examples#52]
When I run `npm run affected:apps` I get the following error:

> nx affected:apps
> Invalid options provided
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! lotes-maps@0.0.0 affected:apps: `nx affected:apps`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the lotes-maps@0.0.0 affected:apps script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:

That is my current configuration:

```
Angular CLI: 6.0.1
Node: 8.11.3
OS: win32 x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by Yonet** [comment]
@dgroh thank you for filing the issue on nx repo. I will close this one.
