### ISSUE TITLE
ng test not picking up all tests in shared libraries

### ISSUE THREAD

**Issue by poppahorse** [nrwl/nx-examples#59]
As per [docs](https://github.com/nrwl/nx-examples#running-unit-tests), running `ng test` only runs 2 tests (which btw both fail). It looks like across the shared libs and apps themselves there are 32 `*.spec.ts` files.

Is it possible that from an apps `karma.conf.js` file, that I can specify spec paths within shared libs to include as part of that apps tests?

Basically what I am trying to do, setup a karma.conf that can then just run the test suite specifically for that app. The majority of functionality is in shared libs, and app logic is minimal, but when working on an app I want to be able to run tests specific to that app in 1 go.

Right now we have something like:
```
ng test --project=app --watch=false && ng test --project=lib_x --watch=false && ng test --project=lib_y --watch=false && ng test --project=lib_z --watch=false
```

The problem with this is that the more shared libs we have, the overhead for the tests gets considerably larger, building modules etc, and tests that used to take 1m ish are now taking 5>m locally, and even longer on ci runners.

**Comment by JVHeerden** [comment]
Any feedback on this yet? I am also have the scenario where I just want to run tests for an app and it's related libraries, without individually specifying all 30 libraries being used

**Comment by poppahorse** [comment]
A long time ago now, but iirc we dropped nrwl and used Angular 6's workspaces instead.

Then in the `tests.ts` (https://github.com/angular/angular/blob/master/aio/src/test.ts) we'd just create a new context for the libs dir as well. You can go further and specify specific libs for specific workspaces if required.

```
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// Load the modules within current project.
context.keys().map(context);
// Find all test in libs
const libs = require.context('./../../libs/', true, /\.spec\.ts$/);
// Load the modules within libs.
libs.keys().map(libs);
```
